import ProviderContainer from "@/context/providers";
import type { Metadata } from "next";

import "./globals.css";
import "react-toastify/dist/ReactToastify.css";

export const metadata: Metadata = {
	title: "Portfolio App V2",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
	return (
		<html>
			<body className="w-full min-h-screen box-border bg-gradient-to-l from-black from-10% via-gray-900 via-50% to-black to-90% text-white">
				<ProviderContainer>{children}</ProviderContainer>
			</body>
		</html>
	);
}
